default_language_version:
  python: python3.9

exclude: ^.git/
  ^__pycache__/

fail_fast: true

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix, --indent=2]
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        types: [python]

  - repo: https://github.com/myint/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --remove-unused-variables,
          ]
        types: [python]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Isort
        additional_dependencies: [toml]
        args: [--sp=setup.cfg, -p=code]
        stages:
          - commit
        types: [python]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
        stages:
          - commit
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--ignore=A003, --max-line-length=120]
        types: [python]
        additional_dependencies:
          - flake8-builtins
          - flake8-print
          - flake8-debugger
          - flake8-commas
          - flake8-comprehensions
          - flake8-eradicate

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
