on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - run: |
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements/dev.txt
        - run: flake8 .
        - run: pytest
